inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Metrics/BlockLength:
  Max: 91

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/admin/user_sessions_controller.rb'

Layout/LineLength:
  Max: 198

Metrics/MethodLength:
  Max: 13